services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container_name-api
    environment:
      - PYTHONPATH=/app/src
      - CELERY_BROKER_URL=redis://:redis-password-here@redis:6379/0
      - CELERY_RESULT_BACKEND=redis://:redis-password-here@redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - shared-network
    # Use watch only in development:
    # see: https://docs.astral.sh/uv/guides/integration/docker/#configuring-watch-with-docker-compose
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /app
    #       ignore:
    #         - .venv/
    #     - action: rebuild
    #       path: ./pyproject.toml
networks:
  shared-network:
    driver: bridge